#!/usr/bin/env php
<?php

require_once __DIR__.'/GithubcmpCli/bootstrap.php';

use GithubcmpCli\Command\CmpCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new CmpCommand());
$application->run();
