#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Doctrine\Common\Annotations\AnnotationRegistry;
use GithubcmpCli\Command\CmpCommand;
use Symfony\Component\Console\Application;

AnnotationRegistry::registerAutoloadNamespace('Githubcmp', __DIR__.'/vendor/ostretsov/githubcmp');

$application = new Application();
$application->add(new CmpCommand());
$application->run();
