<?php

/**
 * (c) Artem Ostretsov <artem@ostretsov.ru>
 * Created at 06.01.2016 07:19.
 */

namespace GithubcmpCli\Renderer;

use Doctrine\Common\Annotations\AnnotationReader;
use Githubcmp\Annotation\Weight;
use Githubcmp\Model\Repository;
use Symfony\Component\Console\Helper\Table;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\PropertyAccess\PropertyAccess;

class CliRenderer extends AbstractRenderer
{
    /**
     * @var OutputInterface
     */
    protected $output;

    public function __construct(OutputInterface $output)
    {
        $this->output = $output;
    }

    public function render(array $repositories, array $options)
    {
        // output results
        $i = 1;
        $reflectedClass = new \ReflectionClass(Repository::class);
        $reader = new AnnotationReader();
        $propertyAccessor = PropertyAccess::createPropertyAccessor();
        $this->output->writeln(sprintf('Generation time: %s', date('m-d-Y H:i')));
        foreach ($repositories as $repository) {
            /* @var Repository $repository */
            $this->output->writeln('');
            $this->output->writeln(sprintf('%d. %s with %d%%', $i, $repository->username.'/'.$repository->repository, $repository->getRating()));
            $this->output->writeln('');

            // prepare rows for table rendering
            $rows = [];
            foreach ($reflectedClass->getProperties() as $property) {
                foreach ($reader->getPropertyAnnotations($property) as $annotation) {
                    if ($annotation instanceof Weight) {
                        // TODO Move to Comparator (get* function)
                        $weight = isset($options[$property->name]) && $options[$property->name] > 0 ? $options[$property->name] : $annotation->value;
                        $rows[] = [
                            ucfirst(strtolower(preg_replace('/([^A-Z])([A-Z])/', '$1 $2', $property->name))),
                            $propertyAccessor->getValue($repository, $property->name),
                            $weight,
                            $propertyAccessor->getValue($repository, $property->name) * $weight,
                        ];
                    }
                }
            }

            usort($rows, function ($a, $b) {
                return $b[3] - $a[3];
            });
            $rows[] = ['Total', '', '', sprintf('%01.2f', $repository->getWeight())];

            $resultTable = new Table($this->output);
            $resultTable
                ->setHeaders(['Key', 'Value', 'Weight', 'Rating'])
                ->setRows($rows)
            ;
            $resultTable->render();
            $this->output->writeln(sprintf('Absolute rating: %01.2f', $repository->getWeight()));

            ++$i;
        }

        // finalize output
        $this->output->writeln('');
        $this->output->writeln('Generated by https://github.com/ostretsov/githubcmp-cli');
    }
}
